### ISSUE TITLE
Private repository clone not working

### ISSUE THREAD

**Issue by lethevimlet** [spckio/spck-issues#29]
Private repository clone fails silently without any error information.

**Comment by AlanPainter** [comment]
Thank you for your effort with this project.
I tried a public GitHub https://github.com/AlanPainter/spckPublic and it failed as well.
![MountGitHub](https://user-images.githubusercontent.com/8102659/57398270-97600500-719c-11e9-9390-087e9316ffbd.JPG)
![ErrorMessage](https://user-images.githubusercontent.com/8102659/57398274-9c24b900-719c-11e9-8d7b-9aa3f7f11948.JPG)

**Comment by k41c** [comment]
+1

**Comment by IDaveYoung** [comment]
Also experiencing

**Comment by spck-io** [comment]
Is this for Github, Gitlab, Bitbucket, or some other host?

**Comment by IDaveYoung** [comment]
I am having issues when using GitHub, I don't use any of the other integrations.

Is there any logging I would be able to get for you, to help with the issue?

Thanks

**Comment by spck-io** [comment]
I have fixed this problem for gitlab. Unfortunately I do not have a private GitHub account to test private repos. This change is pushed to the latest editor version (0.6.0, which can be checked under the settings tab menu).

For 0.6.0 I will aim to fix all git integration issues with the editor.

**Comment by IDaveYoung** [comment]
Would it help if I provided you a token to my private git repo?

**Comment by spck-io** [comment]
I have released a new android app 2.0.1. This was a bug in the android proxy that somehow only affected private repo cloning. Let me know if you experience issue after updating the android app. The proxy is needed as the app runs in a webview and Gitlab, Github, Bitbucket automatically rejects CORS.

**Comment by pankajsays** [comment]
I am trying to clone locally hosted gitea private repository. It errors out saying not found. I am able to clone with git clone https://user:token@url.git

**Comment by spck-io** [comment]
Are you using an app token or a password? I have encountered this for gitlab and found when the app token doesn’t have the permissions to read/write to the repo, it will spit back a 404 error.

**Comment by pankajsays** [comment]
I tried with token, it did not work. I made the repo public, then also it did not work.

**Comment by spck-io** [comment]
I’m using service workers and isomorphic git for the git stuff. Could you share a link of the public repo that’s not working for you? I still suspect for the public repo case there’s something wrong with your token, you can delete it and try, I never had any issues with cloning public repos. Are you checking off read and write repo options when creating the token? Maybe try checking off all the permission scopes for the token? Also right now git sub modules are not supported by isomorphic git, but it shouldn’t prevent cloning.

**Comment by zxsanny** [comment]
Bitbucket clone from private repo doesn't work as well. Used app token. Says "clone failed because http url could not be found"

**Comment by dnazirso** [comment]
Same as @zxsanny `clone failed because http url could not be found`

**Comment by spck-io** [comment]
Please update Android app to version 3.0.6 and let me know if there are any further problems with cloning.

**Comment by orestis-z** [comment]
I have the same issue for bitbucket repos (both public and private) on v3.0.8. Getting `clone failed because http url could not be found`  too

**Comment by spck-io** [comment]
There seemed it be a problem specifically with Bitbucket. One issue that was fixed was the clone URL Bitbucket provided has a username which the HTML fetch API didn’t like. The git library the editor uses, parses out the username into a header which Bitbucket also didn’t like. This issue has been fixed in a editor version 0.9.6.

**Comment by orestis-z** [comment]
Great, is the fix pushed to the play store already?

**Comment by ghost** [comment]
> Bitbucket clone from private repo doesn't work as well. Used app token. Says "clone failed because http url could not be found"

I'm getting the same issue with GitHub on a private repo

**Comment by spck-io** [comment]
Have you upgraded to the latest android app 3.0.12? Make sure to create an app token with full repository access rights. I have just cloned a private repo yesterday from bitbucket. If you are unsure about the access rights, just check all the boxes. Some hosts returns a 404 when the token does not have read permissions to the repo

**Comment by orestis-z** [comment]
Still can't pull public repo on 3.1.0
Trying to pull this one: https://bitbucket.org/zamponotiropita/opsworks-cookbooks.git

**Comment by spck-io** [comment]
I updated the editor to 3.1.1. It seems like sometimes Bitbucket is returning an empty HTTP status message with a 200 status code which was throwing off the proxy server in Android (To avoid browser CORS issues). This was fixed by manually looking up the status message for each status code in the latest version.

**Comment by orestis-z** [comment]
Ok works. Seems like my credentials are removed everytime that I update the android up. Which is a problem since I have to recreate the token each time as I can copy it only once from bitbucket

**Comment by orestis-z** [comment]
Update: seems like credentials lost even without update (can't pull anymore)

**Comment by spck-io** [comment]
Git credentials have been moved to a file in the recent update, it is no longer stored using localStorage, this should prevent loss of credentials between updates or randomly.

**Comment by Vivraan** [comment]
I get this when I try to pull from a public or private repo from GitHub, which I "clone" (the app basically restarts once the option is chosen).

![Screenshot_2020-08-13-19-13-15-59](https://user-images.githubusercontent.com/12777564/90141925-5ee4a900-dd99-11ea-8320-b30d7f2e4bed.jpg)

**Comment by desoter** [comment]
Hello, I have this issue when cloning a private git repository, hosted on my server. I get "HTTP 301 moved permanently" but from any desktop environment it works fine. Also, I only have https (443) channel active on the server so the redirect message makes no sense to me.
Let me know if I can provide more info to help understand the issue.
Thank you!

Edit: my issue is now solved!

**Comment by Mohammad-hosen** [comment]
![Screenshot_2021-06-08-15-03-07-44](https://user-images.githubusercontent.com/83907907/121171184-fb6fbe80-c877-11eb-861b-5c9d5f2f4c6e.jpg)

I am facing problem whenever i pull the file from spck editor. Its saying this. How can i fix this?

**Comment by m0h4mm4d-h053n** [comment]
![Screenshot_2021-06-08-16-37-37-81](https://user-images.githubusercontent.com/83907907/121171951-fb23f300-c878-11eb-9ce0-8a2242322a00.jpg)
I am facing problem whenever i pull the file from spck editor. Its saying can't read poperty lenth of null. How can i fix this?

**Comment by ghost** [comment]
On my android tablet, it is stuck on **fetching pack file**

**Comment by Timberwavy** [comment]
Please how do I fix this
![Uploading Screenshot_20210728-044154.png…]()

**Comment by inxomnyaa** [comment]
Latest Android version and i am hitting this on private repos 
![Screenshot_20220515-041426~2](https://user-images.githubusercontent.com/8733998/168454344-542fd007-1155-4830-bed7-8216388f456a.png)

**Comment by Kazuto** [comment]
I'm still having this issue to this day. I've tried the classic token and the new token type but I can't clone or push to my repos, even when checking all permissions when creating a token. 


**EDIT**
I've found the issue. It was a space after the token. 

![Screenshot_2024-06-25-09-31-06-919_io.spck-edit.jpg](https://github.com/spckio/spck-issues/assets/25435034/550bfda3-c79a-45bd-8cb6-7a8038acf58f)
